# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b41470b6b7af8c01e6e6faf2826c3e3ab64590d819ac83beae1081b8c0e546a0e9d16b3d7ef9ec57bf3ebaa8de6d283b99b827af8fd7f4bf24cdccb0a0c263a

test:
  secret_key_base: 5fad9bfe7387e5acb3c1025e4d32d136f3b645dfc5e37068de9dd63f681454b7ac7d9b42231584977b0c89b6cdd275655f3eede563bcc0c579cd7618fbfa5f48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
